#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.4 on Sat Nov 30 19:25:00 2019

import wx, gettext, abc
from _metaclasses import FrameABCMeta

class BaseFrame(wx.Frame, metaclass=FrameABCMeta):
    def __init__(self, *args, **kwds):
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 300))
        self.notebook_1 = wx.Notebook(self, wx.ID_ANY)
        self.notebook_1_pane_1 = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.text_value1 = wx.TextCtrl(self.notebook_1_pane_1, wx.ID_ANY, "")
        self.radiobox_operator = wx.RadioBox(self.notebook_1_pane_1, wx.ID_ANY, "", choices=[_("+"), _("-"), _("*"), _("/")], majorDimension=1, style=wx.RA_SPECIFY_ROWS)
        self.text_value2 = wx.TextCtrl(self.notebook_1_pane_1, wx.ID_ANY, "")
        self.text_result = wx.TextCtrl(self.notebook_1_pane_1, wx.ID_ANY, "", style=wx.TE_MULTILINE | wx.TE_READONLY)
        self.button_execute = wx.Button(self.notebook_1_pane_1, wx.ID_ANY, _("Execute"))
        self.button_execute.Bind(wx.EVT_BUTTON, self.button_execute_onclick)
        self.button_reset = wx.Button(self.notebook_1_pane_1, wx.ID_ANY, _("Reset"))
        self.button_reset.Bind(wx.EVT_BUTTON, self.button_reset_onclick)
        self.notebook_1_Log = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.text_log = wx.TextCtrl(self.notebook_1_Log, wx.ID_ANY, "", style=wx.TE_MULTILINE | wx.TE_READONLY)
        self.__set_properties()
        self.__do_layout()

    def __set_properties(self):
        self.SetTitle(_("Calculator"))
        self.radiobox_operator.SetSelection(0)
        self.text_result.SetBackgroundColour(wx.Colour(212, 208, 200))
        self.button_execute.SetDefault()
        self.text_log.SetBackgroundColour(wx.Colour(212, 208, 200))

    def __do_layout(self):
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_1 = wx.FlexGridSizer(0, 2, 0, 0)
        label_1 = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, _("Value 1:"))
        grid_sizer_1.Add(label_1, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.text_value1, 1, wx.EXPAND, 0)
        label_4 = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, _("Operator:"))
        grid_sizer_1.Add(label_4, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.radiobox_operator, 0, wx.ALIGN_CENTER, 0)
        label_2 = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, _("Value 2:"))
        grid_sizer_1.Add(label_2, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.text_value2, 1, wx.EXPAND, 0)
        label_3 = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, _("Result:"))
        grid_sizer_1.Add(label_3, 0, 0, 0)
        grid_sizer_1.Add(self.text_result, 1, wx.EXPAND, 0)
        grid_sizer_1.AddGrowableRow(3)
        grid_sizer_1.AddGrowableCol(1)
        sizer_2.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        sizer_7.Add(self.button_execute, 0, wx.ALL, 5)
        sizer_7.Add(self.button_reset, 0, wx.ALL, 5)
        sizer_2.Add(sizer_7, 0, wx.ALIGN_CENTER, 0)
        self.notebook_1_pane_1.SetSizer(sizer_2)
        sizer_8.Add(self.text_log, 1, wx.EXPAND, 0)
        self.notebook_1_Log.SetSizer(sizer_8)
        self.notebook_1.AddPage(self.notebook_1_pane_1, _("Calculate"))
        self.notebook_1.AddPage(self.notebook_1_Log, _("Log"))
        sizer_1.Add(self.notebook_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
    
    @abc.abstractmethod
    def button_execute_onclick(self, e): pass
    
    @abc.abstractmethod
    def button_reset_onclick(self, e): pass